# Generated by Django 4.2.3 on 2023-07-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('title2', models.CharField(max_length=100)),
                ('votes_count', models.IntegerField()),
                ('rating', models.FloatField()),
                ('subtitle_download_url', models.CharField(blank=True, default='', max_length=1000)),
                ('video_stream_url', models.CharField(blank=True, default='', max_length=1000)),
                ('hidden_to_users', models.BooleanField(default=True)),
            ],
        ),
    ]
