# Generated by Django 4.2.3 on 2023-07-21 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='rating',
            new_name='imdb_rating',
        ),
    ]
