# Generated by Django 4.2.3 on 2023-07-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_manager', '0002_rename_rating_movie_imdb_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
