# Generated by Django 4.2.3 on 2023-07-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_manager', '0004_movie_is_inserted_in_elasticsearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='subtitle_download_url',
        ),
    ]
