# Generated by Django 4.2.3 on 2023-08-17 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_manager', '0005_remove_movie_subtitle_download_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video_stream_url',
        ),
    ]
