# Generated by Django 4.2.3 on 2023-08-17 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_manager', '0006_remove_movie_video_stream_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='hidden_to_users',
            new_name='visible',
        ),
    ]
