# Generated by Django 4.2.3 on 2023-08-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_manager', '0008_movie_specific_stream_url_alter_movie_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='specific_stream_url',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
