# Generated by Django 4.2.3 on 2023-08-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_manager', '0010_alter_movie_specific_stream_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='subtitle_file',
            field=models.FileField(blank=True, null=True, upload_to='subtitle_files/'),
        ),
    ]
