# Generated by Django 4.2.3 on 2023-08-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_manager', '0011_movie_subtitle_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='subtitle_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
