# Generated by Django 4.2.3 on 2023-08-19 21:15

from django.db import migrations, models
import movies_manager.utils


class Migration(migrations.Migration):

    dependencies = [
        ('movies_manager', '0012_alter_movie_subtitle_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='is_inserted_in_elasticsearch',
        ),
        migrations.AlterField(
            model_name='movie',
            name='subtitle_file',
            field=models.FileField(blank=True, null=True, upload_to=movies_manager.utils.get_subtitle_path),
        ),
    ]
