# Generated by Django 4.2.3 on 2023-08-18 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies_manager', '0009_alter_movie_specific_stream_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreprocessingMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_url', models.CharField(max_length=1000)),
                ('use_proxy_to_download', models.BooleanField(default=False)),
                ('downloading_trys', models.IntegerField(default=0)),
                ('converting_trys', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('Q', 'Waiting in queue'), ('D', 'Downloading...'), ('C', 'Converting...'), ('S', 'Successful!'), ('F', 'Failed!')], default='Q', max_length=20)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_manager.movie')),
            ],
        ),
    ]
